export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';

export const LOADING_START = 'LOADING_START';
export const LOADING_END = 'LOADING_END';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const UNSET_CURRENT_USER = 'UNSET_CURRENT_USER';

export const GET_ALL_USERS = 'GET_ALL_USERS';
export const CLEAR_USERS_LIST = 'CLEAR_USERS_LIST';
export const UPDATE_USER_BY_ID = 'UPDATE_USER_BY_ID';

export const SET_RESOURCES = 'SET_RESOURCES';